name: cmake-and-upload
author: gendloop
description: 'cmake-and-upload'
inputs:
# Required
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3
      with: 
        token: ${{ inputs.token }}
        submodules: 'recursive'
    
    - name: cmake-x86
      working-directory: ${{ github.workspace }}/scripts
      shell: powershell
      run: |
        ./cmake.ps1 -generator "Visual Studio 16 2019" -platform "x86"

    - name: cmake-x64
      working-directory: ${{ github.workspace }}/scripts
      shell: powershell
      run: |
        ./cmake.ps1 -generator "Visual Studio 16 2019" -platform "x64"

    - name: get-version
      id: get_version
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        version=$(cat config.txt)
        major=$(echo $version | grep -o "VERSION_MAJOR=[0-9]*" | cut -d'=' -f2)
        minor=$(echo $version | grep -o "VERSION_MINOR=[0-9]*" | cut -d'=' -f2)
        patch=$(echo $version | grep -o "VERSION_PATCH=[0-9]*" | cut -d'=' -f2)
        final_version=v${major}.${minor}.${patch}
        echo $final_version
        echo "CURR_VERSION=$final_version" >> "$GITHUB_OUTPUT"

    # - name: upload-release-assets
    #   uses: gendloop/upload-release-assets@main
    #   with:
    #     releaseTag: ${{ steps.get_version.outputs.CURR_VERSION }}
    #     githubToken: ${{ inputs.token }}
    #     files: |
    #       ./upload/*.zip
    #     overrideExistingArtefact: true

    - name: upload-release-assets
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        file: "./upload/*.zip"
        tag_name: ${{ steps.get_version.outputs.CURR_VERSION }}
        overwrite: true



